// <auto-generated />
using System;
using DDDSample1.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDNetCore.Migrations
{
    [DbContext(typeof(DDDSample1DbContext))]
    partial class DDDSample1DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("DDDSample1.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DDDSample1.Domain.Families.Family", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("DDDSample1.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("dddnetcore.Domain.AfetacaoMensais.AfetacaoMensal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AfetacaoPerfilId")
                        .HasColumnType("TEXT");

                    b.Property<double>("PMs")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AfetacaoPerfilId");

                    b.ToTable("AfetacaoMensais");
                });

            modelBuilder.Entity("dddnetcore.Domain.AfetacaoPerfis.AfetacaoPerfil", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracaoMes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PMsAprovados")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("AfetacaoPerfis");
                });

            modelBuilder.Entity("dddnetcore.Domain.Atividades.Atividade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFimAtividade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicioAtividade")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoAtividade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAtividade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrcamentoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjetoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("dddnetcore.Domain.CargasMensais.CargaMensal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Ausencias")
                        .HasColumnType("REAL");

                    b.Property<double>("DiasUteis")
                        .HasColumnType("REAL");

                    b.Property<double>("JornadaDiaria")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("MesAno")
                        .HasColumnType("TEXT");

                    b.Property<double>("SalarioBase")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("CargasMensais");
                });

            modelBuilder.Entity("dddnetcore.Domain.Contratos.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<double>("Salario")
                        .HasColumnType("REAL");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("dddnetcore.Domain.Entregaveis.Entregavel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TipoEntregavelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TipoEntregavelId");

                    b.ToTable("Entregaveis");
                });

            modelBuilder.Entity("dddnetcore.Domain.Indicadores.Indicador", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Indicadores");
                });

            modelBuilder.Entity("dddnetcore.Domain.Orcamentos.Orcamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("GastoExecutado")
                        .HasColumnType("REAL");

                    b.Property<double>("GastoPlaneado")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RubricaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RubricaId");

                    b.ToTable("Orcamentos");
                });

            modelBuilder.Entity("dddnetcore.Domain.Perfis.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("dddnetcore.Domain.Projetos.Projeto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("dddnetcore.Domain.Rubricas.Rubrica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rubricas");
                });

            modelBuilder.Entity("dddnetcore.Domain.Tarefas.Tarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AtividadeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoTarefa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeTarefa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusTarefa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("dddnetcore.Domain.TiposEntregavel.TipoEntregavel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposEntregavel");
                });

            modelBuilder.Entity("dddnetcore.Domain.TiposVinculo.TipoVinculo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposVinculo");
                });

            modelBuilder.Entity("dddnetcore.Domain.AfetacaoMensais.AfetacaoMensal", b =>
                {
                    b.HasOne("dddnetcore.Domain.AfetacaoPerfis.AfetacaoPerfil", "AfetacaoPerfil")
                        .WithMany()
                        .HasForeignKey("AfetacaoPerfilId");

                    b.Navigation("AfetacaoPerfil");
                });

            modelBuilder.Entity("dddnetcore.Domain.Atividades.Atividade", b =>
                {
                    b.HasOne("dddnetcore.Domain.Orcamentos.Orcamento", "Orcamento")
                        .WithMany()
                        .HasForeignKey("OrcamentoId");

                    b.HasOne("dddnetcore.Domain.Projetos.Projeto", null)
                        .WithMany("Atividades")
                        .HasForeignKey("ProjetoId");

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("dddnetcore.Domain.Entregaveis.Entregavel", b =>
                {
                    b.HasOne("dddnetcore.Domain.TiposEntregavel.TipoEntregavel", "TipoEntregavel")
                        .WithMany()
                        .HasForeignKey("TipoEntregavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoEntregavel");
                });

            modelBuilder.Entity("dddnetcore.Domain.Indicadores.Indicador", b =>
                {
                    b.HasOne("dddnetcore.Domain.Projetos.Projeto", null)
                        .WithMany("Indicadores")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("dddnetcore.Domain.Indicadores.NomeIndicador", "Nome", b1 =>
                        {
                            b1.Property<Guid>("IndicadorId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("NomeIndicador");

                            b1.HasKey("IndicadorId");

                            b1.ToTable("Indicadores");

                            b1.WithOwner()
                                .HasForeignKey("IndicadorId");
                        });

                    b.OwnsOne("dddnetcore.Domain.Indicadores.ValorAtual", "ValorAtual", b1 =>
                        {
                            b1.Property<Guid>("IndicadorId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Valor")
                                .HasColumnType("REAL")
                                .HasColumnName("ValorAtual");

                            b1.HasKey("IndicadorId");

                            b1.ToTable("Indicadores");

                            b1.WithOwner()
                                .HasForeignKey("IndicadorId");
                        });

                    b.OwnsOne("dddnetcore.Domain.Indicadores.ValorMaximo", "ValorMaximo", b1 =>
                        {
                            b1.Property<Guid>("IndicadorId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Valor")
                                .HasColumnType("REAL")
                                .HasColumnName("ValorMaximo");

                            b1.HasKey("IndicadorId");

                            b1.ToTable("Indicadores");

                            b1.WithOwner()
                                .HasForeignKey("IndicadorId");
                        });

                    b.Navigation("Nome");

                    b.Navigation("ValorAtual");

                    b.Navigation("ValorMaximo");
                });

            modelBuilder.Entity("dddnetcore.Domain.Orcamentos.Orcamento", b =>
                {
                    b.HasOne("dddnetcore.Domain.Rubricas.Rubrica", "Rubrica")
                        .WithMany()
                        .HasForeignKey("RubricaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rubrica");
                });

            modelBuilder.Entity("dddnetcore.Domain.Perfis.Perfil", b =>
                {
                    b.HasOne("dddnetcore.Domain.Projetos.Projeto", null)
                        .WithMany("Perfis")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("dddnetcore.Domain.Perfis.DescricaoPerfil", "DescricaoPerfil", b1 =>
                        {
                            b1.Property<Guid>("PerfilId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("DescricaoPerfil");

                            b1.HasKey("PerfilId");

                            b1.ToTable("Perfil");

                            b1.WithOwner()
                                .HasForeignKey("PerfilId");
                        });

                    b.OwnsOne("dddnetcore.Domain.Perfis.PMsTotais", "PMs", b1 =>
                        {
                            b1.Property<Guid>("PerfilId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Valor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PMsTotais");

                            b1.HasKey("PerfilId");

                            b1.ToTable("Perfil");

                            b1.WithOwner()
                                .HasForeignKey("PerfilId");
                        });

                    b.Navigation("DescricaoPerfil")
                        .IsRequired();

                    b.Navigation("PMs")
                        .IsRequired();
                });

            modelBuilder.Entity("dddnetcore.Domain.Projetos.Projeto", b =>
                {
                    b.OwnsOne("dddnetcore.Domain.Projetos.DescricaoProjeto", "DescricaoProjeto", b1 =>
                        {
                            b1.Property<Guid>("ProjetoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("DescricaoProjeto");

                            b1.HasKey("ProjetoId");

                            b1.ToTable("Projetos");

                            b1.WithOwner()
                                .HasForeignKey("ProjetoId");
                        });

                    b.OwnsOne("dddnetcore.Domain.Projetos.NomeProjeto", "NomeProjeto", b1 =>
                        {
                            b1.Property<Guid>("ProjetoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("NomeProjeto");

                            b1.HasKey("ProjetoId");

                            b1.ToTable("Projetos");

                            b1.WithOwner()
                                .HasForeignKey("ProjetoId");
                        });

                    b.Navigation("DescricaoProjeto");

                    b.Navigation("NomeProjeto");
                });

            modelBuilder.Entity("dddnetcore.Domain.Tarefas.Tarefa", b =>
                {
                    b.HasOne("dddnetcore.Domain.Atividades.Atividade", null)
                        .WithMany("Tarefas")
                        .HasForeignKey("AtividadeId");
                });

            modelBuilder.Entity("dddnetcore.Domain.Atividades.Atividade", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("dddnetcore.Domain.Projetos.Projeto", b =>
                {
                    b.Navigation("Atividades");

                    b.Navigation("Indicadores");

                    b.Navigation("Perfis");
                });
#pragma warning restore 612, 618
        }
    }
}
