@startuml domain-model
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

skinparam packageStyle rectangle

package "<<Aggregate>> Atividade" #C2B078 {
    entity Atividade <<entity>> <<root>>
    class NomeAtividade <<Value Object>>
    class DescricaoAtividade <<Value Object>>
}

package "<<Aggregate>> Bolseiro" #7F7679 {
    entity Bolseiro <<entity>> <<root>>
}

package "<<Aggregate>> Contrato" #5D9B9B {
    entity Contrato <<entity>> <<root>>
    class DataInicio <<Value Object>>
    class DataFim <<Value Object>>
    enum TipoContrato <<Value Object>> {
        Normal
        Bolsa
    }
    'TODO verificar ligações
}

package "<<Aggregate>> DadosPessoais" #999950 {
    entity DadosPessoais <<entity>> <<root>>
    class Nome <<Value Object>>
    class Email <<Value Object>>
    class CienciaID <<Value Object>>
    'TODO perguntar se os investigadores são funcionalmente iguais a bolseiros
}

package "<<Aggregate>> Entregavel" #3E5F8A {
    entity Entregavel <<entity>> <<root>>
    class NomeEntregavel <<Value Object>>
    class DescricaoEntregavel <<Value Object>>
    class DataEntrega <<Value Object>>
}

package "<<Aggregate>> Investigador" #2271B3 {
    entity Investigador <<entity>> <<root>>
}

package "<<Aggregate>> Perfil" #78858B {
    entity Perfil <<entity>> <<root>>
    'TODO verificar isto
}  

package "<<Aggregate>> Projeto" #00BB2D {
    entity Projeto <<entity>> <<root>>
    class Titulo <<Value Object>>
    class Numero <<Value Object>>
    class Indicador <<Value Object>>
}

package "<<Aggregate>> Orcamento" #FF7514 {
    entity Orcamento <<entity>> <<root>>
    class Receita <<Value Object>>
    class Despesa <<Value Object>>
    'TODO verificar isto
}

package "<<Aggregate>> Rubrica" #6C3B2A {
    entity Rubrica <<entity>> <<root>>
    class NomeRubrica <<Value Object>>
    'TODO verificar isto
}

package "<<Aggregate>> Tarefa" #EDFF21 {
    entity Tarefa <<entity>> <<root>>
    class NomeTarefa <<Value Object>>
    class DescricaoTarefa <<Value Object>>
    enum Status <<Value Object>> {
        Por_Comecar
        A_Decorrer
        Terminado
    }
    '? progresso?
}

package "<<Aggregate>> TipoEntregavel" #57A639 {
    entity TipoEntregavel <<entity>> <<root>>
    class NomeTipoEntregavel <<Value Object>>
}

Atividade --> NomeAtividade
Atividade --> DescricaoAtividade
Atividade "1" ---> "*" Tarefa
Atividade "1" ---> "*" Perfil
Atividade "1" ---> "*" Entregavel

DadosPessoais "0..1" <--- "1" Bolseiro

Contrato --> DataInicio
Contrato --> DataFim
Contrato --> TipoContrato
Contrato "*" ---> "1" Bolseiro 

DadosPessoais --> Nome
DadosPessoais --> Email
DadosPessoais --> CienciaID 

Entregavel --> NomeEntregavel
Entregavel --> DescricaoEntregavel
Entregavel --> DataEntrega
Entregavel "*" ---> "1" TipoEntregavel

Investigador "1" ---> "0..1" DadosPessoais

Perfil "1" ---> "1" Contrato

Projeto --> Titulo
Projeto --> Numero
Projeto --> Indicador
Projeto "1" -> "*" Atividade
Projeto "1" ---> "1" Orcamento
Projeto "*" ---> "*" Investigador

Orcamento --> Receita
Orcamento --> Despesa
Orcamento "1" ---> "1" Rubrica

Rubrica --> NomeRubrica

Tarefa --> NomeTarefa
Tarefa --> DescricaoTarefa
Tarefa --> Status
Orcamento "1" <--- "1" Tarefa

TipoEntregavel --> NomeTipoEntregavel

@enduml